### ISSUE TITLE
newick-1.2 

### ISSUE THREAD

**Issue by jbsinclair** [vagarwal87/TargetScanTools#3]
The link to http://www.daimi.au.dk/~mailund/newick/newick-1.2.tar.gz is disabled.

**Comment by vagarwal87** [comment]
Thanks for pointing this out. My scripts depend on http://motifmap.ics.uci.edu/downloads/BranchLengthScoring.py which in turn depend on that package. Since it's a third-party package, I'm not sure what to suggest other than possibly contacting the MotifMap authors to provide you a copy, or possibly the original author who ended up removing the link to provide you the .tar.gz file.

**Comment by jbsinclair** [comment]
I don't know who the author is but following your suggestion I emailed the department of computer science (daimi) at Aarhus University and am waiting on their reply. Thanks.
